#docker -ti run -d -p 80:8081 --name nexusoss -v /opt/nexus/data:/nexus-data sonatype/nexus:oss
version: '3'
services:
    nginx:
        image: sonatype/nexus:oss
        container_name: nexusoss
        ports:
            - "80:8081"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - /opt/nexus/data:/nexus-data

